apiVersion: v1
kind: Service
metadata:
  name: shopping-service
  labels:
    name: shopping-service
    app: beach-shirt-app
    

spec:
  type: LoadBalancer
  ports:
    - targetPort: 50050
      port: 80

  selector:
      name: shopping-app-pod
      app: beach-shirt-app
