apiVersion: apps/v1
# Kubernetes versions after 1.9.0 should use apps/v1
# Kubernetes versions before 1.8.0 should use apps/v1beta1 or extensions/v1beta1
kind: Deployment
metadata:
  name: wavefront-proxy
  namespace: default
  labels:
   app: wavefront-proxy
   name: wavefront-proxy
spec:
  replicas: 1
  selector:
   matchLabels:
    app: wavefront-proxy
  template:
    metadata:
      labels:
        app: wavefront-proxy
    spec:
      containers:
      - name: wavefront-proxy
        image: "us.gcr.io/wavefront-gcp-dev/akodali/wavefront-proxy-withmetrics"
        imagePullPolicy: Always
        env:
        - name: WAVEFRONT_URL
          value: https://virunga.wavefront.com/api/
        - name: WAVEFRONT_TOKEN
          value: a1656497-850f-4bba-ac9d-a6ae12764efe
        - name: WAVEFRONT_PROXY_ARGS
          value: --traceZipkinListenerPorts 9411
        ports:
        - containerPort: 2878
          protocol: TCP
        - containerPort: 9411
        securityContext:
          privileged: 
---
apiVersion: v1
kind: Service
metadata:
  name: wavefront-proxy
  labels:
    app: wavefront-proxy
spec:
  ports:
  - name: wavefront
    port: 2878
    protocol: TCP
  - name: http
    port: 9411
    targetPort: 9411
    protocol: TCP
  selector:
    app: wavefront-proxy