server:
  applicationConnectors:
  - type: http
    port: 50050
  adminConnectors:
  - type: http
    port: 50150

stylingPort: 50051
stylingHost: "localhost"

metadata:
  application: beachshirts
  cluster: us-west
  service: shopping
  shard: primary
  customTags:
    location: Palo-Alto
    env: production

wavefrontReporting:
  reportingMechanism: "DIRECT"
  server: "replace-with-wavefront-url"
  token: "wavefront-token"
  flushIntervalSeconds: 1
  source: wavefront-source20