server:
  applicationConnectors:
  - type: http
    port: 50050
  adminConnectors:
  - type: http
    port: 50150

stylingPort: 50051
printingPort: 50052
packagingPort: 50053

application: beachshirts
host: source1
cluster: us-west
service: shopping
shard: primary

tags:
  location: Palo-Alto