server:
  applicationConnectors:
  - type: http
    port: 50051
  adminConnectors:
  - type: http
    port: 50151


printingPort: 50052
packagingPort: 50053

printingHost: "localhost"
packagingHost: "localhost"

metadata:
  application: beachshirts
  cluster: us-west
  service: styling
  shard: primary
  customTags:
    location: Palo-Alto
    env: production

wavefrontReporting:
  reportingMechanism: "DIRECT"
  server: "replace-with-wavefront-url"
  token: "wavefront-token"
  flushIntervalSeconds: 1
  source: wavefront-source20